---
   - name: Update Installed Packages
   apt: upgrade=dist update_cache=yes
   when: apt-update

   - name: installing packages
   package: name={{item}} state=present
   with_items: "{{packages}}"
